In [3]:
import numpy as np

In [4]:
arr=np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
nums= np.array([[1,2,3],[4,5,6]])
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(arr.shape)

(5,)


In [7]:
print(arr.ndim)

1


In [8]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Evenly Spaced Numbers:


In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Array Properties:


In [14]:
print(arr.ndim)   
print(arr.shape)  
print(arr.size)  #total elements
print(arr.dtype)  #data type of elements
print(arr.itemsize)

1
(5,)
5
int64
8


Type Conversion:

In [15]:
arr= np.array([1.2,2.5,3.7])
arr_int= arr.astype(int)
print(arr_int)

[1 2 3]


In [16]:
arr= np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [17]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30 50]


2D Indexing:

In [18]:
mat= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [19]:
print(mat[:,1])

[2 5 8]


In [20]:
a= np.array([1,2,3])
b= a.copy()
#b=a #this creates a reference not a copy, any change in b whill also change a
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [21]:
a= np.array([1,2,3])
b= np.array([4,5,6])

Basic Array Operations:


In [22]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)



[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar operations:


In [23]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


unfus(universal functions):

In [24]:
arr=np.array([1,4,9,16])

print(np.sqrt(arr))  #square root
print(np.log(arr))   #natural logarithm
print(np.exp(arr))   #exponential
print(np.sin(arr))   #sine
print(np.cos(arr))   #cosine
print(np.mean(arr))  #mean
print(np.median(arr))#median
print(np.std(arr))   #standard deviation
print(np.sum(arr))   #sum of elements
print(np.min(arr))   #minimum element
print(np.max(arr))   #maximum element
print(np.sort(arr))  #sorted array


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
7.5
6.5
5.678908345800274
30
1
16
[ 1  4  9 16]


Boolean Indexing:

In [25]:
arr = np.array([10,20,30,40,50])
print(arr[arr>25])  #elements greater than 25

[30 40 50]


In [26]:
print(arr>25)

[False False  True  True  True]


Broadcasting Rules:


In [27]:
#Numpy automatically expands smaller errays

In [28]:
arr= np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [30]:
mat= np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [31]:
row= np.array([1,2,3])
print(mat+row)  #broadcasting row to each row of the matrix

[[2 4 6]
 [5 7 9]]


Matrix Multiplication:


In [ ]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
print(np.dot(A,B))  #if we don't use dot it will do elementwise multiplication instead of matrix multiplication

[[19 22]
 [43 50]]


In [34]:
print(A.T)  #transpose of A

[[1 3]
 [2 4]]


Random Module:

In [35]:
np.random.rand(5)  #5 random numbers between 0 and 1

array([0.03150861, 0.68246317, 0.24161297, 0.16339229, 0.63955969])

In [36]:
np.random.rand(3,3)  #3x3 matrix of random numbers between 0 and 1

array([[0.78388581, 0.42060468, 0.9996173 ],
       [0.99622079, 0.2961182 , 0.30298694],
       [0.69597012, 0.05817326, 0.14437275]])

In [37]:
np.random.randint(1,100,10)  #10 random integers between 1 and 100

array([ 4, 47, 37,  2, 48, 74, 97, 91, 41, 96], dtype=int32)

In [38]:
np.random.randint(1,10,size=(3,3))  #3x3 matrix of random integers between 1 and 10

array([[7, 3, 1],
       [6, 8, 4],
       [9, 2, 7]], dtype=int32)

Reshaping Arrays:

In [40]:
arr= np.arange(12)
print(arr.reshape(3,4))  #reshaping to 3 rows and 4 columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


axis in numpy:


In [41]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [42]:
print(np.sum(arr))

21


In [43]:
print(np.sum(arr,axis=0))  #sum along columns

[5 7 9]


In [44]:
print(np.sum(arr,axis=1))  #sum along rows

[ 6 15]


where in numpy:


In [45]:
arr= np.array([10,-5,20,-3,15])

In [46]:
result = np.where(arr>0, 'Positive', 'Negative')
print(result)

['Positive' 'Negative' 'Positive' 'Negative' 'Positive']


In [47]:
result= np.where(arr<0,0,arr)  #replace negative values with 0
print(result)

[10  0 20  0 15]


In [48]:
arr= np.array([1,2,3,4,5])

In [49]:
result= np.where(arr%2 !=0,-1,arr)  #replace odd values with -1
print(result)

[-1  2 -1  4 -1]


In [50]:
marks= np.array([45,78,32,90,55])

In [51]:
status= np.where(marks>=50,'Pass','Fail')
print(status)

['Fail' 'Pass' 'Fail' 'Pass' 'Pass']


In [52]:
data= np.array([10,20,30,40,50])

In [53]:
mean_val = np.mean(data)
result= np.where(data> mean_val,mean_val,data)  #replace values greater than mean with mean value
print(result)

[10. 20. 30. 30. 30.]


applying (where) condition in 2d array:

In [57]:
mat= np.array([
    [10,60,30],
    [80,20,90],     
])

In [58]:
result= np.where(mat>50,1,0)  #replace values greater than 50 with 1 and others with 0
print(result)

[[0 1 0]
 [1 0 1]]
