In [1]:
import numpy as np


In [3]:
marks = np.array([[78,85,90],[72,68,33],[99,24,56],[88,92,80],[65,84,69]])

In [4]:
print(marks.shape)
print(marks.ndim)
print(marks.size)
print(marks.dtype)

(5, 3)
2
15
int64


In [5]:
print(marks[1:2])
print(marks[:,2])
print(marks[0,1])


[[72 68 33]]
[90 33 56 80 69]
85


In [7]:
print(np.min(marks))
print(np.average(marks, axis=0))
print(np.average(marks, axis=1))
print(np.max(marks))

24
[80.4 70.6 65.6]
[84.33333333 57.66666667 59.66666667 86.66666667 72.66666667]
99


In [10]:
# identify and display students having avaerage marks >=80
high_achievers= marks[np.average(marks, axis=1) >= 80]
print(high_achievers)

[[78 85 90]
 [88 92 80]]


In [9]:
# add 5 grace marks to every subject for all students
marks_with_grace= marks + 5

In [11]:
#create a status matrix where marks >= 50 is pass(1) and marks < 50 is fail(0)
status_matrix = np.where(marks >= 50, 1, 0)
print(status_matrix)

[[1 1 1]
 [1 1 0]
 [1 0 1]
 [1 1 1]
 [1 1 1]]
