In [60]:
import numpy as np

In [61]:
arr=np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [62]:
nums= np.array([[1,2,3],[4,5,6]])
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
print(arr.shape)

(5,)


In [64]:
print(arr.ndim)

1


In [65]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Evenly Spaced Numbers:


In [70]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Array Properties:


In [71]:
print(arr.ndim)   
print(arr.shape)  
print(arr.size)  #total elements
print(arr.dtype)  #data type of elements
print(arr.itemsize)

1
(5,)
5
int64
8


Type Conversion:

In [72]:
arr= np.array([1.2,2.5,3.7])
arr_int= arr.astype(int)
print(arr_int)

[1 2 3]


In [73]:
arr= np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [74]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30 50]


2D Indexing:

In [75]:
mat= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [76]:
print(mat[:,1])

[2 5 8]


In [77]:
a= np.array([1,2,3])
b= a.copy()
#b=a #this creates a reference not a copy, any change in b whill also change a
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [78]:
a= np.array([1,2,3])
b= np.array([4,5,6])

Basic Array Operations:


In [79]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)



[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar operations:


In [80]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


unfus(universal functions):

In [81]:
arr=np.array([1,4,9,16])

print(np.sqrt(arr))  #square root
print(np.log(arr))   #natural logarithm
print(np.exp(arr))   #exponential
print(np.sin(arr))   #sine
print(np.cos(arr))   #cosine
print(np.mean(arr))  #mean
print(np.median(arr))#median
print(np.std(arr))   #standard deviation
print(np.sum(arr))   #sum of elements
print(np.min(arr))   #minimum element
print(np.max(arr))   #maximum element
print(np.sort(arr))  #sorted array


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
7.5
6.5
5.678908345800274
30
1
16
[ 1  4  9 16]


Boolean Indexing:

In [82]:
arr = np.array([10,20,30,40,50])
print(arr[arr>25])  #elements greater than 25

[30 40 50]


In [83]:
print(arr>25)

[False False  True  True  True]


Broadcasting Rules:


In [84]:
#Numpy automatically expands smaller errays

In [85]:
arr= np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [86]:
mat= np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [87]:
row= np.array([1,2,3])
print(mat+row)  #broadcasting row to each row of the matrix

[[2 4 6]
 [5 7 9]]


Matrix Multiplication:


In [88]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
print(np.dot(A,B))  #if we don't use dot it will do elementwise multiplication instead of matrix multiplication

[[19 22]
 [43 50]]


In [89]:
print(A.T)  #transpose of A

[[1 3]
 [2 4]]


Random Module:

In [90]:
np.random.rand(5)  #5 random numbers between 0 and 1

array([0.22470676, 0.41634746, 0.91561358, 0.5421486 , 0.2913754 ])

In [91]:
np.random.rand(3,3)  #3x3 matrix of random numbers between 0 and 1

array([[0.27861058, 0.90178885, 0.44974159],
       [0.59591581, 0.39438118, 0.17463638],
       [0.27489486, 0.10079542, 0.92231356]])

In [92]:
np.random.randint(1,100,10)  #10 random integers between 1 and 100

array([97, 27, 17, 33,  3, 53, 48,  3, 12, 74], dtype=int32)

In [93]:
np.random.randint(1,10,size=(3,3))  #3x3 matrix of random integers between 1 and 10

array([[2, 3, 7],
       [8, 1, 2],
       [9, 6, 5]], dtype=int32)

Reshaping Arrays:

In [94]:
arr= np.arange(12)
print(arr.reshape(3,4))  #reshaping to 3 rows and 4 columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


axis in numpy:


In [95]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [96]:
print(np.sum(arr))

21


In [97]:
print(np.sum(arr,axis=0))  #sum along columns

[5 7 9]


In [98]:
print(np.sum(arr,axis=1))  #sum along rows

[ 6 15]


where in numpy:


In [99]:
arr= np.array([10,-5,20,-3,15])

In [100]:
result = np.where(arr>0, 'Positive', 'Negative')
print(result)

['Positive' 'Negative' 'Positive' 'Negative' 'Positive']


In [101]:
result= np.where(arr<0,0,arr)  #replace negative values with 0
print(result)

[10  0 20  0 15]


In [102]:
arr= np.array([1,2,3,4,5])

In [103]:
result= np.where(arr%2 !=0,-1,arr)  #replace odd values with -1
print(result)

[-1  2 -1  4 -1]


In [104]:
marks= np.array([45,78,32,90,55])

In [105]:
status= np.where(marks>=50,'Pass','Fail')
print(status)

['Fail' 'Pass' 'Fail' 'Pass' 'Pass']


In [106]:
data= np.array([10,20,30,40,50])

In [107]:
mean_val = np.mean(data)
result= np.where(data> mean_val,mean_val,data)  #replace values greater than mean with mean value
print(result)

[10. 20. 30. 30. 30.]


applying (where) condition in 2d array:

In [108]:
mat= np.array([
    [10,60,30],
    [80,20,90],     
])

In [109]:
result= np.where(mat>50,1,0)  #replace values greater than 50 with 1 and others with 0
print(result)

[[0 1 0]
 [1 0 1]]


In [110]:
cost_price= np.array([1500,3000,5000])

In [111]:
daily_sales=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(daily_sales)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [112]:
print(daily_sales.shape)  #shape of the array


(3, 4)


In [113]:
daily_sales= (daily_sales+2)

In [114]:
print(daily_sales)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [115]:
print(np.sqrt(daily_sales))  #square root of each element in the array

[[3.46410162 4.12310563 3.16227766 3.74165739]
 [2.64575131 3.         2.44948974 2.82842712]
 [2.         2.23606798 2.         2.44948974]]


In [116]:
print(np.dot(cost_price,daily_sales))  #matrix multiplication of cost_price and daily_sales

[59000 77500 53000 75000]


In [ ]:
# sales data of row 1:
print(daily_sales[0])

[12 17 10 14]


In [119]:
#sales data for first 2 days:
print(daily_sales[:,:2])

[[12 17]
 [ 7  9]
 [ 4  5]]


In [ ]:
# access the sales of speakers on thursday using double indexing
print(daily_sales[0,3])

14


In [121]:
#extract 2x2 submatrix of sales for first 2 days and first 2 products
print(daily_sales[:2,:2])

[[12 17]
 [ 7  9]]


Task 4:


In [122]:
#flatten 3x4 daily_sales array into 1d array of 122 elements using .reshape()
print(daily_sales.reshape(-1))

[12 17 10 14  7  9  6  8  4  5  4  6]


In [123]:
print(daily_sales.reshape(2,6))

[[12 17 10 14  7  9]
 [ 6  8  4  5  4  6]]


In [125]:
print(np.linspace(0,100,10))


[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [126]:
#use np.random.randit to genertae a new 3x4 array of predicted sales for next weekk value ranging from 0 to 20
predicted_sales= np.random.randint(0,20,size=(3,4))

In [127]:
print(predicted_sales)

[[ 2 19  3 11]
 [17  2 17 15]
 [ 4 10  6 19]]


In [128]:
#generate a random array of 5 numbers between 0 and 1 using np.random.rand
random_array= np.random.rand(5)